version: "3.3"
networks:
   mysql-database:
services:
    db-mysql:
        image: mysql/mysql-server:5.6
        container_name: openshr-db-mysql
        volumes:
            - ./openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
        env_file:
            - db.env
        ports:
            - "3308:3306"
        networks:
          - mysql-database
    db-postgres:
        image: postgres:9.3
        container_name: openshr-db-postgres
        env_file:
            - db.env
        ports:
            - "5432:5432"
        networks:
          - postgres-database
    webapp:
        image: tomcat:7-jre7-alpine
        container_name: openshr-tomcat
        depends_on:
            - db-mysql
        volumes:
            - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./modules:/root/.OpenMRS/modules
        ports:
            - "8081:8080"
        networks:
            - mysql-database