version: "3.3"
networks:
    mysql-database:
    postgres-database:
services:
    openshr-mysql:
        image: mysql/mysql-server:5.6
        container_name: openshr-mysql
        env_file:
            - db.env
        volumes:
            - ./openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
            - ./openmrs_db_config.sql:/docker-entrypoint-initdb.d/openmrs_db_config.sql
        ports:
            - "3308:3306"
        networks:
          - mysql-database
    openshr-postgres:
        image: postgres:9.6
        container_name: postgresql-openxds
        networks:
            - postgres-database
    openshr-openmrs:
        image: tomcat:7.0-jre7-alpine
        container_name: openshr-openmrs
        depends_on:
            - openshr-mysql
        volumes:
            - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./modules:/root/.OpenMRS/modules
        ports:
            - "8082:8080"
        networks:
            - mysql-database
    openshr-openxds:
        image: uwitech/openxds
        container_name: openshr-openxds
        volumes:
            - ./XdsCodes.xml:/opt/openxds/conf/actors/XdsCodes.xml
        ports:
            - "8010:8010"
            - "8020:8020"
        depends_on:
            - openshr-postgres
        networks:
            - postgres-database