version: "3.3"
networks:
    mysql-database:
    postgres-database:
services:
    db-mysql:
        image: mysql/mysql-server:5.6
        container_name: openshr-db-mysql
        volumes:
            - ./openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
        env_file:
            - db.env
        ports:
            - "3308:3306"
        networks:
          - mysql-database
    db-postgres:
        image: postgres:9.3
        container_name: postgresql-openxds
        env_file:
            - db.env
        volumes:
            - ./create_database_schema_postgres.sql:/docker-entrypoint-initdb.d/create_database_schema_postgres.sql
        networks:
            - postgres-database
    webapp:
        image: tomcat:7-jre7-alpine
        container_name: openshr-tomcat
        depends_on:
            - db-mysql
        volumes:
            - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./modules:/root/.OpenMRS/modules
        ports:
            - "8082:8080"
        networks:
            - mysql-database
    openxds:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: openshr-openxds
        env_file:
            - db.env
        ports:
            - "8010:8010"
            - "8020:8020"
        depends_on:
            - db-postgres
        networks:
            - postgres-database